# Generated by Django 6.0 on 2025-12-10 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Dirección de Entrega')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('project_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=50)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono')),
                ('other_windows', models.TextField(blank=True, null=True, verbose_name='Notas / Otras Ventanas')),
                ('other_windows_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Adicional')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50, verbose_name='Alto')),
                ('width', models.CharField(max_length=50, verbose_name='Ancho')),
                ('line', models.CharField(max_length=100, verbose_name='Línea')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('crystal', models.CharField(max_length=100, verbose_name='Cristal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('material_cut', models.BooleanField(default=False, verbose_name='Corte Material')),
                ('glass_cut', models.BooleanField(default=False, verbose_name='Corte Vidrio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='core.project')),
            ],
        ),
    ]
